### ISSUE TITLE
Obsolete readme | Pélopée != stellaire

### ISSUE THREAD

**Issue by guillaumecabanel** [nfilzi/nfilzi#1]
You should update the last part mentioning "Pélopée" instead of [stellaire.studio](https://www.stellaire.studio/)

**Comment by nfilzi** [comment]
@guillaumecabanel, just removed the whole section. I'm working on revamping my personal website → https://about.nfilzi.com

Thanks for the feedback. As always, you're the sniper!

**Comment by guillaumecabanel** [comment]
![image](https://github.com/user-attachments/assets/2b285bf4-cef4-497c-8746-6b7c56d9d18a)
